"""Enable ON DELETE CASCADE for cart foreign keys

Revision ID: dc303c9befd2
Revises: 3bd04159c9ca
Create Date: 2025-06-18 18:32:28.738587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc303c9befd2'
down_revision = '3bd04159c9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cart_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('cart_ibfk_1'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###
